### PR TITLE
rkt cleanup

### PR DESCRIPTION
**Pull request by carlwgeorge**
* use `--enable-tpm=auto` configure flag
* add tmpfiles.d file
* use systemd-sysusers to add rkt group

### CODE REVIEW

**Comment by carlwgeorge** [comment]
The other things we talked about in the AUR comments I can't do, because the changes from [this commit](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=rkt&id=7b04f1416da92c3927ffd53d7ba99f76488cf1f7) haven't been applied here.

**Comment by yuvadm** [comment]
@carlwgeorge sorry, forgot to push :) just did that

**Comment by yuvadm** [comment]
Also make sure to add yourself as a contributor as the top of the file

**Comment by carlwgeorge** [comment]
All cleaned up now with those fixes.

**Comment by yuvadm** [comment]
Squashed and merged manually

**Pull request closed without merging**
