### PR TITLE
Rocket needs the stage1.aci file in the same location as the rkt binary

### PR DESCRIPTION
**Pull request by rasschaert**
See https://github.com/coreos/rocket/issues/457#issuecomment-73936693

### CODE REVIEW

**Comment by yuvadm** [comment]
@rasschaert Interesting bug! However, I don't believe putting `stage1.aci` in `/usr/bin` is a solution that should be done on the package level. If I understand correctly you can specific the location for this file? In that case, that should be the workaround, and not polluting `/usr/bin`.

If I didn't understand the nature of the bug, I'm open to being convinced otherwise.

**Comment by yuvadm** [comment]
And actually, @jonboulle mentioned the exact fix here https://github.com/coreos/rocket/issues/457#issuecomment-73944496

If you go ahead and implement that, I'll gladly merge the fix :)

**Comment by rasschaert** [comment]
As far as I can tell the [the code that tells rkt where stage1.aci is](https://github.com/coreos/rocket/blob/68a0c0b6567a3e9b2feb4fbf476f1730f27b6fb5/rkt/run.go#L51-L56) can't be changed with a build option. It assumes stage1.aci is in the same directory as the rkt binary unless the --stage1-image option is given on the command line.

Do you reckon I should open an issue upstream to add that option to the build script?

**Comment by yuvadm** [comment]
@rasschaert absolutely, this is a blocking upstream fix.

**Comment by rasschaert** [comment]
Filed at https://github.com/coreos/rocket/issues/520

**Comment by yuvadm** [comment]
Hmm, what does line 58 do, then? https://github.com/coreos/rocket/blob/68a0c0b6567a3e9b2feb4fbf476f1730f27b6fb5/rkt/run.go#L58

**Comment by rasschaert** [comment]
They added the option to specify your own stage1 file at runtime:
```
rkt run --stage1-image=/path/to/stage1.aci example.com/app
```
Without that option rkt just dies with:
```
Error finding stage1 image "/usr/bin/stage1.aci": rkt only supports http or https URLs (/usr/bin/stage1.aci)
```
There doesn't appear to be a build option to change the default location where rkt looks for the stage1 file.

**Comment by jonboulle** [comment]
Sorry about that guys - just fixed upstream. You'll just need to set `RKT_STAGE1_IMAGE` to the appropriate location (for where you will actually write stage1.aci to disk) when running the build script. Let us know if you have any other problems!

**Comment by jonboulle** [comment]
(also to be clear; this is on master now, and will make it into the next tagged release, probably next week)

**Comment by yuvadm** [comment]
@jonboulle thanks for the quick fix! @rasschaert would you like to update the patch so we have it ready for the release?

**Comment by rasschaert** [comment]
Been looking into it. The source archive doesn't seem like a good base to build on because of https://github.com/coreos/rocket/issues/522.

Probably best to wait until that gets resolved or to go forward using a git clone and check out the correct tag.

**Comment by yuvadm** [comment]
There's [rocket-git](https://aur.archlinux.org/packages/rocket-git/) which isn't maintained by me, you can try to ping the maintainer about it.

**Comment by rasschaert** [comment]
It'd be nice to have a reproducible package for the tagged releases, like what you had before.

When building from the source .tar.gz or a git tag, you can even support other architectures. :smiley:

**Comment by rasschaert** [comment]
Updated the PKGBUILD for rocket again so that it builds from the source archive and sets ```RKT_STAGE1_IMAGE``` to ```/usr/lib/rkt/stage1.aci```.

Also took the liberty of adding myself as a contributor at the top of the file.

**Comment by yuvadm** [comment]
@rasschaert looks great! I'm curious why the source path changed, what happened there?

Will test and merge soon :) Thanks!

**Comment by rasschaert** [comment]
I should probably have bumped pkgrel to 2, since you had already put out a PKGBUILD on AUR for v0.3.2. Want another PR for that or will you just edit that in yourself?

**Pull request merged**
