### PR TITLE
Update sslmate to 1.2.0

### PR DESCRIPTION
**Pull request by AGWA**
Thanks!

### CODE REVIEW

**Comment by yuvadm** [comment]
@AGWA thanks for the PR! Since you're obviously following the development much closer than I am, I'm just hindering the release process here :) If you'd like, I'd be happy to transfer ownership of the AUR package to you.

**Comment by AGWA** [comment]
@yuvadm Yeah, I think that would be a good idea.  My AUR username is AGWA.  Thanks for creating the package in the first place and maintaining it up until now.

**Comment by yuvadm** [comment]
@AGWA I've disowned it, please adopt it ASAP

**Comment by AGWA** [comment]
@yuvadm Done.

**Pull request merged**
